import type { Patient, AnalyticsData } from '../types';

export const mockPatients: Patient[] = [
  {
    id: 'P001',
    name: 'Arjun Mehta',
    age: 45,
    gender: 'Male',
    bloodType: 'O+',
    phone: '+91 98765 43210',
    email: 'arjun.mehta@email.com',
    address: '12, Marine Drive, Mumbai, MH',
    condition: 'Hypertension',
    status: 'Active',
    doctor: 'Dr. Priya Sharma',
    admittedDate: '2024-01-15',
    lastVisit: '2024-03-20',
    diagnosis: 'Stage 2 Hypertension with risk of cardiac complications',
    medications: ['Amlodipine 5mg', 'Losartan 50mg', 'Aspirin 75mg'],
    allergies: ['Penicillin', 'Sulfa drugs'],
    vitals: { bp: '148/95', pulse: 82, temp: '98.6°F', oxygen: 97 },
    ward: 'Cardiology',
    insuranceId: 'INS-2024-001',
  },
  {
    id: 'P002',
    name: 'Sneha Patel',
    age: 32,
    gender: 'Female',
    bloodType: 'A+',
    phone: '+91 87654 32109',
    email: 'sneha.patel@email.com',
    address: '45, Bandra West, Mumbai, MH',
    condition: 'Diabetes Type 2',
    status: 'Active',
    doctor: 'Dr. Rajesh Kumar',
    admittedDate: '2024-02-08',
    lastVisit: '2024-03-19',
    diagnosis: 'Type 2 Diabetes Mellitus, uncontrolled',
    medications: ['Metformin 1000mg', 'Glipizide 5mg', 'Vitamin D3'],
    allergies: ['Latex'],
    vitals: { bp: '125/80', pulse: 76, temp: '98.4°F', oxygen: 98 },
    ward: 'Endocrinology',
    insuranceId: 'INS-2024-002',
  },
  {
    id: 'P003',
    name: 'Ravi Krishnamurthy',
    age: 67,
    gender: 'Male',
    bloodType: 'B-',
    phone: '+91 76543 21098',
    email: 'ravi.k@email.com',
    address: '78, Andheri East, Mumbai, MH',
    condition: 'Coronary Artery Disease',
    status: 'Critical',
    doctor: 'Dr. Sunita Verma',
    admittedDate: '2024-03-01',
    lastVisit: '2024-03-21',
    diagnosis: 'CAD with left ventricular dysfunction',
    medications: ['Carvedilol 25mg', 'Furosemide 40mg', 'Spironolactone 25mg', 'Digoxin 0.25mg'],
    allergies: ['Iodine', 'Contrast dye'],
    vitals: { bp: '155/100', pulse: 94, temp: '99.1°F', oxygen: 93 },
    ward: 'Cardiac ICU',
    insuranceId: 'INS-2024-003',
  },
  {
    id: 'P004',
    name: 'Meera Iyer',
    age: 28,
    gender: 'Female',
    bloodType: 'AB+',
    phone: '+91 65432 10987',
    email: 'meera.iyer@email.com',
    address: '23, Powai, Mumbai, MH',
    condition: 'Asthma',
    status: 'Active',
    doctor: 'Dr. Amit Desai',
    admittedDate: '2024-03-10',
    lastVisit: '2024-03-18',
    diagnosis: 'Moderate persistent asthma',
    medications: ['Fluticasone inhaler', 'Salbutamol inhaler', 'Montelukast 10mg'],
    allergies: ['Aspirin', 'NSAIDs'],
    vitals: { bp: '118/75', pulse: 72, temp: '98.2°F', oxygen: 96 },
    ward: 'Pulmonology',
    insuranceId: 'INS-2024-004',
  },
  {
    id: 'P005',
    name: 'Vikram Singh',
    age: 54,
    gender: 'Male',
    bloodType: 'O-',
    phone: '+91 54321 09876',
    email: 'vikram.singh@email.com',
    address: '156, Chembur, Mumbai, MH',
    condition: 'Kidney Disease',
    status: 'Active',
    doctor: 'Dr. Priya Sharma',
    admittedDate: '2024-02-20',
    lastVisit: '2024-03-21',
    diagnosis: 'Chronic Kidney Disease Stage 3',
    medications: ['Erythropoietin injection', 'Calcium carbonate', 'Iron supplement'],
    allergies: ['None known'],
    vitals: { bp: '138/88', pulse: 78, temp: '98.8°F', oxygen: 97 },
    ward: 'Nephrology',
    insuranceId: 'INS-2024-005',
  },
  {
    id: 'P006',
    name: 'Lakshmi Nair',
    age: 41,
    gender: 'Female',
    bloodType: 'A-',
    phone: '+91 43210 98765',
    email: 'lakshmi.nair@email.com',
    address: '89, Thane West, Mumbai, MH',
    condition: 'Rheumatoid Arthritis',
    status: 'Discharged',
    doctor: 'Dr. Rajesh Kumar',
    admittedDate: '2024-01-05',
    lastVisit: '2024-03-15',
    diagnosis: 'Seropositive Rheumatoid Arthritis',
    medications: ['Methotrexate 15mg weekly', 'Prednisolone 5mg', 'Folic acid 5mg'],
    allergies: ['Shellfish'],
    vitals: { bp: '122/78', pulse: 70, temp: '98.3°F', oxygen: 99 },
    ward: 'Rheumatology',
    insuranceId: 'INS-2024-006',
  },
  {
    id: 'P007',
    name: 'Ananya Das',
    age: 19,
    gender: 'Female',
    bloodType: 'B+',
    phone: '+91 32109 87654',
    email: 'ananya.das@email.com',
    address: '34, Goregaon, Mumbai, MH',
    condition: 'Anxiety Disorder',
    status: 'Active',
    doctor: 'Dr. Sunita Verma',
    admittedDate: '2024-03-05',
    lastVisit: '2024-03-20',
    diagnosis: 'Generalized Anxiety Disorder with panic attacks',
    medications: ['Sertraline 50mg', 'Clonazepam 0.5mg PRN', 'Vitamin B complex'],
    allergies: ['None known'],
    vitals: { bp: '115/72', pulse: 88, temp: '98.1°F', oxygen: 99 },
    ward: 'Psychiatry',
    insuranceId: 'INS-2024-007',
  },
  {
    id: 'P008',
    name: 'Deepak Gupta',
    age: 72,
    gender: 'Male',
    bloodType: 'AB-',
    phone: '+91 21098 76543',
    email: 'deepak.gupta@email.com',
    address: '67, Worli, Mumbai, MH',
    condition: 'Parkinson\'s Disease',
    status: 'Active',
    doctor: 'Dr. Amit Desai',
    admittedDate: '2024-01-25',
    lastVisit: '2024-03-17',
    diagnosis: 'Parkinson\'s Disease, Stage 3',
    medications: ['Levodopa/Carbidopa', 'Ropinirole 4mg', 'Selegiline 5mg'],
    allergies: ['Codeine'],
    vitals: { bp: '130/82', pulse: 68, temp: '98.5°F', oxygen: 96 },
    ward: 'Neurology',
    insuranceId: 'INS-2024-008',
  },
  {
    id: 'P009',
    name: 'Kavitha Reddy',
    age: 36,
    gender: 'Female',
    bloodType: 'O+',
    phone: '+91 10987 65432',
    email: 'kavitha.r@email.com',
    address: '101, Malad West, Mumbai, MH',
    condition: 'Migraine',
    status: 'Inactive',
    doctor: 'Dr. Priya Sharma',
    admittedDate: '2024-02-14',
    lastVisit: '2024-03-10',
    diagnosis: 'Chronic migraine with aura',
    medications: ['Topiramate 100mg', 'Sumatriptan 50mg PRN', 'Amitriptyline 25mg'],
    allergies: ['Codeine', 'Tramadol'],
    vitals: { bp: '120/76', pulse: 74, temp: '98.4°F', oxygen: 98 },
    ward: 'Neurology',
    insuranceId: 'INS-2024-009',
  },
  {
    id: 'P010',
    name: 'Suresh Menon',
    age: 58,
    gender: 'Male',
    bloodType: 'A+',
    phone: '+91 09876 54321',
    email: 'suresh.menon@email.com',
    address: '55, Kandivali East, Mumbai, MH',
    condition: 'Liver Cirrhosis',
    status: 'Critical',
    doctor: 'Dr. Rajesh Kumar',
    admittedDate: '2024-03-08',
    lastVisit: '2024-03-21',
    diagnosis: 'Liver cirrhosis with portal hypertension',
    medications: ['Propranolol 40mg', 'Spironolactone 100mg', 'Rifaximin 550mg'],
    allergies: ['Penicillin'],
    vitals: { bp: '118/70', pulse: 96, temp: '99.8°F', oxygen: 95 },
    ward: 'Hepatology',
    insuranceId: 'INS-2024-010',
  },
  {
    id: 'P011',
    name: 'Pooja Shah',
    age: 23,
    gender: 'Female',
    bloodType: 'B+',
    phone: '+91 98765 11223',
    email: 'pooja.shah@email.com',
    address: '78, Borivali West, Mumbai, MH',
    condition: 'Thyroid Disorder',
    status: 'Active',
    doctor: 'Dr. Sunita Verma',
    admittedDate: '2024-02-28',
    lastVisit: '2024-03-19',
    diagnosis: 'Hypothyroidism - Hashimoto\'s thyroiditis',
    medications: ['Levothyroxine 50mcg', 'Selenium supplement', 'Vitamin D3'],
    allergies: ['None known'],
    vitals: { bp: '116/74', pulse: 64, temp: '97.8°F', oxygen: 99 },
    ward: 'Endocrinology',
    insuranceId: 'INS-2024-011',
  },
  {
    id: 'P012',
    name: 'Rahul Joshi',
    age: 49,
    gender: 'Male',
    bloodType: 'O+',
    phone: '+91 87654 22334',
    email: 'rahul.joshi@email.com',
    address: '23, Vasai Road, Mumbai, MH',
    condition: 'Lung Cancer',
    status: 'Critical',
    doctor: 'Dr. Amit Desai',
    admittedDate: '2024-01-10',
    lastVisit: '2024-03-21',
    diagnosis: 'Non-small cell lung cancer, Stage IIIA',
    medications: ['Osimertinib 80mg', 'Ondansetron 8mg', 'Dexamethasone 4mg'],
    allergies: ['Platinum drugs'],
    vitals: { bp: '110/68', pulse: 102, temp: '100.2°F', oxygen: 91 },
    ward: 'Oncology',
    insuranceId: 'INS-2024-012',
  },
];

export const analyticsData: AnalyticsData = {
  totalPatients: 1247,
  activePatients: 834,
  criticalPatients: 43,
  dischargedThisMonth: 128,
  avgStayDays: 4.7,
  bedOccupancy: 87,
  monthlyAdmissions: [
    { month: 'Oct', admissions: 142, discharges: 128 },
    { month: 'Nov', admissions: 158, discharges: 144 },
    { month: 'Dec', admissions: 134, discharges: 156 },
    { month: 'Jan', admissions: 189, discharges: 172 },
    { month: 'Feb', admissions: 201, discharges: 188 },
    { month: 'Mar', admissions: 176, discharges: 128 },
  ],
  departmentLoad: [
    { dept: 'Cardiology', patients: 145, capacity: 180 },
    { dept: 'Oncology', patients: 98, capacity: 120 },
    { dept: 'Neurology', patients: 112, capacity: 140 },
    { dept: 'Pulmonology', patients: 87, capacity: 100 },
    { dept: 'Nephrology', patients: 76, capacity: 90 },
    { dept: 'Endocrinology', patients: 91, capacity: 110 },
  ],
  conditionBreakdown: [
    { name: 'Cardiac', value: 28, color: '#2563eb' },
    { name: 'Oncology', value: 18, color: '#7c3aed' },
    { name: 'Diabetes', value: 15, color: '#0891b2' },
    { name: 'Respiratory', value: 12, color: '#059669' },
    { name: 'Neurology', value: 14, color: '#d97706' },
    { name: 'Others', value: 13, color: '#94a3b8' },
  ],
  revenueData: [
    { month: 'Oct', revenue: 48.2, expenses: 31.4 },
    { month: 'Nov', revenue: 52.8, expenses: 34.1 },
    { month: 'Dec', revenue: 45.6, expenses: 29.8 },
    { month: 'Jan', revenue: 61.3, expenses: 38.2 },
    { month: 'Feb', revenue: 58.9, expenses: 36.7 },
    { month: 'Mar', revenue: 54.1, expenses: 33.5 },
  ],
};
